export const GET_REGISTONE_FORM='GET_REGISTONE_FORM';
export const SET_REGISTONE_FORM='SET_REGISTONE_FORM';
export const CLEAR_REGISTONE_FORM='CLEAR_REGISTONE_FORM';
export const GET_REGISTTWO_FORM='GET_REGISTTWO_FORM';
export const SET_REGISTTWO_FORM='SET_REGISTTWO_FORM';
export const CLEAR_REGISTTWO_FORM='CLEAR_REGISTTWO_FORM';
export const GET_REGISTTHREE_FORM='GET_REGISTTHREE_FORM';
export const SET_REGISTTHREE_FORM='SET_REGISTTHREE_FORM';
export const CLEAR_REGISTTHREE_FORM='CLEAR_REGISTTHREE_FORM';


